---
framework: mocha
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/*.js"
    - "./test/modules/*.js"
postMerge:
  pattern: 
    - "./test/*.js"
    - "./test/modules/*.js"
postRun:
     command:
        - node --version
configFile: mocharc.yml
nodeVersion: 14.18.3
version: 1.0
